server:
  port: 8081

spring:
  application:
    name: authentication-service

  config:
    import: "optional:configserver:http://localhost:8888"



      # if you’re calling a secure config‐server, you may also need credentials:
      # username: your‐user
      # password: your‐pass
app:
  cors:
    allowed-origins: http://localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/