server:
  port: 8081
spring:
  application:
    name: authentication-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    driver-class-name: org.postgresql.Driver
    username: postgres             #  username for PostgresSQL
    password: 'postgres'            #  password for PostgresSQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000    # 1h

app:
  cors:
    allowed-origins: http://localhost:8080

#spring:
#  application:
#    name: authentication-service
#
#  cloud:
#    config:
#      uri: http://localhost:8888
#      # if you’re calling a secure config‐server, you may also need credentials:
#      # username: your‐user
#      # password: your‐pass