spring:
  application:
    name: config-server-service

  cloud:
    config:
      server:
        native:
          # Order of locations searched for config files
          search-locations:
            - file:./config-repo
            - classpath:/config-repo

  profiles:
    active: native

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
