server:
  port: 8080

spring:
  config:
    import: "optional:configserver:http://localhost:8888"




  application:
    name:
      api-gateway-service

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE
    # You might also want to check if there's a specific logger for routing filters