server:
  port: 8080

spring:
  config:
    import: "optional:configserver://localhost:8888"


  application:
    name:
      api-gateway-service

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


